# Generated by Django 5.0.7 on 2024-07-30 15:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('periodo', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='EstadisticaJugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('campeonato', models.CharField(max_length=100)),
                ('partidosJugados', models.IntegerField()),
                ('goles', models.IntegerField()),
                ('tarjetasAmarillas', models.IntegerField()),
                ('tarjetasRojas', models.IntegerField()),
                ('asistencias', models.IntegerField()),
                ('faltas', models.IntegerField()),
                ('recuperaciones', models.IntegerField()),
                ('mvpPartidos', models.IntegerField()),
                ('mvpCampeonatos', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EstadisticaEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('campeonato', models.CharField(max_length=100)),
                ('partidosJugados', models.IntegerField()),
                ('goles', models.IntegerField()),
                ('tarjetasAmarillas', models.IntegerField()),
                ('tarjetasRojas', models.IntegerField()),
                ('asistencias', models.IntegerField()),
                ('faltas', models.IntegerField()),
                ('recuperaciones', models.IntegerField()),
                ('puntos', models.IntegerField()),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='estadisticas', to='CampeonatoFutbol.equipo')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='equipo',
            name='estadistica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='CampeonatoFutbol.estadisticaequipo'),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cuota', models.FloatField()),
                ('estado', models.CharField(max_length=100)),
                ('equipoInscrito', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='inscripciones', to='CampeonatoFutbol.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='equipo',
            name='inscripcionList',
            field=models.ManyToManyField(blank=True, related_name='equipos_inscripciones', to='CampeonatoFutbol.inscripcion'),
        ),
        migrations.CreateModel(
            name='Jugador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('posicion', models.CharField(max_length=100)),
                ('peso', models.FloatField()),
                ('genero', models.CharField(max_length=100)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='jugadores', to='CampeonatoFutbol.equipo')),
                ('estadistica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jugadores', to='CampeonatoFutbol.estadisticajugador')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='estadisticajugador',
            name='jugador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='estadisticas', to='CampeonatoFutbol.jugador'),
        ),
        migrations.AddField(
            model_name='equipo',
            name='jugadorList',
            field=models.ManyToManyField(blank=True, related_name='equipos', to='CampeonatoFutbol.jugador'),
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(max_length=100)),
                ('equipoLocal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='partidos_local', to='CampeonatoFutbol.inscripcion')),
                ('equipoVisitante', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='partidos_visitante', to='CampeonatoFutbol.inscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Campeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('LIGA', 'Liga'), ('COPA', 'Copa'), ('TORNEO', 'Torneo'), ('GRUPOS', 'Grupos')], max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('periodo', models.CharField(max_length=100)),
                ('inscripcionesList', models.ManyToManyField(blank=True, related_name='campeonatos', to='CampeonatoFutbol.inscripcion')),
                ('partidoList', models.ManyToManyField(blank=True, related_name='campeonatos', to='CampeonatoFutbol.partido')),
            ],
        ),
        migrations.CreateModel(
            name='Arbitro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('ci', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254)),
                ('partidoList', models.ManyToManyField(blank=True, related_name='arbitros', to='CampeonatoFutbol.partido')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esEmpate', models.BooleanField()),
                ('golesLocal', models.IntegerField()),
                ('golesVisitante', models.IntegerField()),
                ('ganador', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ganador_resultados', to='CampeonatoFutbol.equipo')),
                ('partido', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='resultado_partido', to='CampeonatoFutbol.partido')),
                ('perdedor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='perdedor_resultados', to='CampeonatoFutbol.equipo')),
            ],
        ),
        migrations.AddField(
            model_name='partido',
            name='resultado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='partidos_asociados', to='CampeonatoFutbol.resultado'),
        ),
        migrations.CreateModel(
            name='TablaPosiciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puntos', models.IntegerField()),
                ('partidosJugados', models.IntegerField()),
                ('partidosGanados', models.IntegerField()),
                ('partidosEmpatados', models.IntegerField()),
                ('partidosPerdidos', models.IntegerField()),
                ('golesFavor', models.IntegerField()),
                ('golesContra', models.IntegerField()),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tabla_posiciones', to='CampeonatoFutbol.campeonato')),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='posiciones', to='CampeonatoFutbol.equipo')),
                ('estadistica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posiciones', to='CampeonatoFutbol.estadisticaequipo')),
            ],
        ),
    ]
