# Generated by Django 5.0.7 on 2024-08-05 04:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampeonatoFutbol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultadoCampeonato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campeonato', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resultado', to='CampeonatoFutbol.campeonato')),
                ('primerLugar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resultados_ganador', to='CampeonatoFutbol.inscripcion')),
                ('segundoLugar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resultados_subcampeon', to='CampeonatoFutbol.inscripcion')),
                ('tercerLugar', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resultados_tercer_lugar', to='CampeonatoFutbol.inscripcion')),
            ],
        ),
    ]
