# Generated by Django 5.0.7 on 2024-08-05 04:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CampeonatoFutbol', '0002_resultadocampeonato'),
    ]

    operations = [
        migrations.AddField(
            model_name='campeonato',
            name='resultado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='campeonatos', to='CampeonatoFutbol.resultadocampeonato'),
        ),
        migrations.AddField(
            model_name='campeonato',
            name='tablaPosicion',
            field=models.ManyToManyField(blank=True, related_name='campeonatos', to='CampeonatoFutbol.tablaposiciones'),
        ),
        migrations.AlterField(
            model_name='resultadocampeonato',
            name='campeonato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resultados', to='CampeonatoFutbol.campeonato'),
        ),
    ]
